<?xml version="1.0" encoding="UTF-8"?><testrun name="MarsRoversTest" project="Practice2020" tests="6" started="6" failures="0" errors="1" ignored="0">
  <testsuite name="Phoebe.MarsRoversTest" time="0.026">
    <testcase name="turnLeftExceptionTesting" classname="Phoebe.MarsRoversTest" time="0.0"/>
    <testcase name="decodeDirectionCommendsTesting" classname="Phoebe.MarsRoversTest" time="0.025">
      <error>org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type MarsRovers and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
	at Phoebe.MarsRoversTest.decodeDirectionCommendsTesting(MarsRoversTest.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

</error>
    </testcase>
    <testcase name="moveForwardNormalTesting" classname="Phoebe.MarsRoversTest" time="0.0"/>
    <testcase name="turnLeftNormalTesting" classname="Phoebe.MarsRoversTest" time="0.0"/>
    <testcase name="turnRightNormalTesting" classname="Phoebe.MarsRoversTest" time="0.001"/>
    <testcase name="turnRightExceptionTesting" classname="Phoebe.MarsRoversTest" time="0.0"/>
  </testsuite>
</testrun>
